// Inversify identifiers — keep all in one place to avoid circular imports.
export const TOKENS = {
  // config / infra primitives
  Env: Symbol.for('Env'),
  Logger: Symbol.for('Logger'),
  Clock: Symbol.for('Clock'),
  AppUrls: Symbol.for('AppUrls'),

  // repositories (driven ports)
  ItemRepository: Symbol.for('ItemRepository'),
  UserRepository: Symbol.for('UserRepository'),
  MatchRepository: Symbol.for('MatchRepository'),
  ThreadRepository: Symbol.for('ThreadRepository'),
  MessageRepository: Symbol.for('MessageRepository'),
  RewardRepository: Symbol.for('RewardRepository'),
  InstitutionRepository: Symbol.for('InstitutionRepository'),
  InstitutionLeadRepository: Symbol.for('InstitutionLeadRepository'),
  QrTagRepository: Symbol.for('QrTagRepository'),
  QrTagProductRepository: Symbol.for('QrTagProductRepository'),
  QrTagOrderRepository: Symbol.for('QrTagOrderRepository'),
  VerificationRepository: Symbol.for('VerificationRepository'),
  CourierJobRepository: Symbol.for('CourierJobRepository'),
  VaultRepository: Symbol.for('VaultRepository'),
  AuditLogRepository: Symbol.for('AuditLogRepository'),
  ZoneSubscriptionRepository: Symbol.for('ZoneSubscriptionRepository'),
  MarketplaceListingRepository: Symbol.for('MarketplaceListingRepository'),
  PoliceCaseRepository: Symbol.for('PoliceCaseRepository'),
  RefreshTokenRepository: Symbol.for('RefreshTokenRepository'),
  OtpRepository: Symbol.for('OtpRepository'),
  PasswordResetRepository: Symbol.for('PasswordResetRepository'),
  IdempotencyStore: Symbol.for('IdempotencyStore'),
  ReportRepository: Symbol.for('ReportRepository'),
  BlockRepository: Symbol.for('BlockRepository'),
  NotificationRepository: Symbol.for('NotificationRepository'),
  RedemptionRepository: Symbol.for('RedemptionRepository'),
  WebhookRepository: Symbol.for('WebhookRepository'),
  BookmarkRepository: Symbol.for('BookmarkRepository'),
  TrustedFinderApplicationRepository: Symbol.for('TrustedFinderApplicationRepository'),
  PartnerApiKeyRepository: Symbol.for('PartnerApiKeyRepository'),
  ReviewRepository: Symbol.for('ReviewRepository'),

  // services (driven ports)
  PasswordHasher: Symbol.for('PasswordHasher'),
  TokenService: Symbol.for('TokenService'),
  EmailService: Symbol.for('EmailService'),
  SmsService: Symbol.for('SmsService'),
  PushService: Symbol.for('PushService'),
  WebPushService: Symbol.for('WebPushService'),
  PaymentEscrow: Symbol.for('PaymentEscrow'),
  ImageStorage: Symbol.for('ImageStorage'),
  AiMatchingService: Symbol.for('AiMatchingService'),
  AiVerificationService: Symbol.for('AiVerificationService'),
  ContentModeration: Symbol.for('ContentModeration'),
  TextGenerationService: Symbol.for('TextGenerationService'),
  GeocodingService: Symbol.for('GeocodingService'),
  RealtimeBus: Symbol.for('RealtimeBus'),
  PerceptualHash: Symbol.for('PerceptualHash'),
  PdfReportService: Symbol.for('PdfReportService'),
  I18nService: Symbol.for('I18nService'),
  TwilioSignatureVerifier: Symbol.for('TwilioSignatureVerifier'),
  ErrorReporter: Symbol.for('ErrorReporter'),
  Scheduler: Symbol.for('Scheduler'),
  Queue: Symbol.for('Queue'),
  QueueWorker: Symbol.for('QueueWorker'),
  VaultCipher: Symbol.for('VaultCipher'),
  WebPushSubscriptionRepository: Symbol.for('WebPushSubscriptionRepository'),
  ModerationQueueRepository: Symbol.for('ModerationQueueRepository'),
  FeatureFlagRepository: Symbol.for('FeatureFlagRepository'),
  Cache: Symbol.for('Cache'),
} as const;
